# Generated by Django 3.0.7 on 2020-12-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Иконка fontawesome')),
                ('number', models.PositiveIntegerField(default=1, help_text='Указать номер категории по порядку', unique=True, verbose_name='Последовательность')),
                ('user_view', models.BooleanField(default=True, verbose_name='Показывать имена пользователей')),
                ('check_top_category', models.CharField(blank=True, choices=[('1', 'Считать как "В строю"'), ('2', 'Считать как "На удаленке"'), ('3', 'Считать как "В распоряжении"'), ('4', 'Считать как "Отсутствующие"')], max_length=1, null=True, verbose_name='Как учитывать категорию?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='table_in.TableStat')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='UsersShtat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Средний и старший НС'), ('2', 'Рядовой и младший НС'), ('3', 'Служащий')], max_length=2, verbose_name='наименование по штату')),
                ('count_shtat', models.IntegerField(verbose_name='Всего по штату')),
            ],
            options={
                'verbose_name': 'Кол-во по штату',
                'verbose_name_plural': 'Кол-во по штату сотрудников',
            },
        ),
        migrations.CreateModel(
            name='TableUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('doljnost', models.TextField(blank=True, verbose_name='Должность сотрудника')),
                ('user_corona', models.BooleanField(default=False, verbose_name='Проходил обследование на COVID-19?')),
                ('user_vakcina_corona', models.BooleanField(default=False, verbose_name='Проходил вакцинацию от СОVID-19?')),
                ('user_date_range', models.CharField(blank=True, max_length=19, null=True, verbose_name='Период отпуска / больничного / отпуска по личным обстоятельствам')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Подпись')),
                ('users_sign', models.BooleanField(default=False, verbose_name='Использовать подпись?')),
                ('user_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_in.UsersShtat', verbose_name='Категория сотрудника')),
                ('user_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_in.TableStat', verbose_name='Где находится')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
            },
        ),
    ]
