# Generated by Django 3.0.7 on 2020-12-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_in', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableusers',
            name='user_vakcina_corona',
        ),
    ]
