# Generated by Django 3.0.7 on 2020-12-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_in', '0002_remove_tableusers_user_vakcina_corona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableusers',
            name='user_vakcina_corona',
            field=models.BooleanField(default=False, verbose_name='Проходил вакцинацию от СОVID-19?'),
        ),
    ]
