# Generated by Django 4.2.2 on 2023-10-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_in', '0003_tableusers_user_vakcina_corona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableusers',
            options={'ordering': ('name',), 'verbose_name': 'Имя', 'verbose_name_plural': 'Имена'},
        ),
    ]
