# Generated by Django 3.1.1 on 2024-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_in', '0004_alter_tableusers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUsersSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('doljnost', models.TextField(blank=True, verbose_name='Должность сотрудника')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Подпись')),
                ('users_sign', models.BooleanField(default=False, verbose_name='Использовать подпись?')),
            ],
            options={
                'verbose_name': 'Имя подписанта',
                'verbose_name_plural': 'Имена подписантов',
            },
        ),
    ]
