# Generated by Django 3.1.1 on 2024-01-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_in', '0005_tableuserssign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableusers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tableusers',
            name='users_sign',
        ),
    ]
